// Re-exports shadcn/ui's own "cn" package (their compiled drop-in replacement
// for clsx + tailwind-merge) rather than hand-rolling the same thing twice —
// every shadcn component generated by the CLI imports `cn` from "cn"
// directly, so this keeps the whole app on one implementation instead of two
// that could quietly drift apart.
export { cn } from "cn"
