-- Employee records, branch assignments, and the geofencing columns on branches.
--
-- Generated by `prisma migrate diff` against a real Postgres, unlike the four
-- migrations before it, which were hand-written because no database was
-- available at the time.
--
-- Everything here is inert. No code reads the geo columns yet, geofencing is
-- off until real coordinates exist (U10), and no employees are seeded. The
-- columns land now because two of them are expensive to retrofit:
--
--   * masterSource / odooEmployeeId — the platform has to own employee master
--     data until Odoo exists, then hand authority over. Adding that column
--     after employees exist means backfilling ownership for every row.
--   * employee_branch_assignments as many-to-many — relief and cover work is
--     ordinary in restaurant operations, and assuming one branch per employee
--     would have to be undone across every attendance query later.
-- CreateEnum
CREATE TYPE "MasterSource" AS ENUM ('LOCAL', 'ODOO');

-- CreateEnum
CREATE TYPE "EmploymentStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'TERMINATED');

-- AlterTable
ALTER TABLE "branches" ADD COLUMN     "geofenceEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "geofenceRadiusMeters" INTEGER NOT NULL DEFAULT 150,
ADD COLUMN     "latitude" DOUBLE PRECISION,
ADD COLUMN     "longitude" DOUBLE PRECISION,
ADD COLUMN     "maxAcceptableAccuracyMeters" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "odooBranchId" TEXT,
ADD COLUMN     "timezone" TEXT NOT NULL DEFAULT 'Africa/Accra';

-- CreateTable
CREATE TABLE "employees" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "employeeCode" TEXT NOT NULL,
    "odooEmployeeId" TEXT,
    "masterSource" "MasterSource" NOT NULL DEFAULT 'LOCAL',
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "jobTitle" TEXT,
    "hireDate" TIMESTAMP(3),
    "terminationDate" TIMESTAMP(3),
    "status" "EmploymentStatus" NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "employees_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "employee_branch_assignments" (
    "id" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "branchId" TEXT NOT NULL,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,
    "validFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "validTo" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "employee_branch_assignments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "employees_userId_key" ON "employees"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "employees_employeeCode_key" ON "employees"("employeeCode");

-- CreateIndex
CREATE UNIQUE INDEX "employees_odooEmployeeId_key" ON "employees"("odooEmployeeId");

-- CreateIndex
CREATE INDEX "employees_status_idx" ON "employees"("status");

-- CreateIndex
CREATE INDEX "employees_masterSource_idx" ON "employees"("masterSource");

-- CreateIndex
CREATE INDEX "employee_branch_assignments_employeeId_validFrom_idx" ON "employee_branch_assignments"("employeeId", "validFrom");

-- CreateIndex
CREATE INDEX "employee_branch_assignments_branchId_validFrom_idx" ON "employee_branch_assignments"("branchId", "validFrom");

-- CreateIndex
CREATE UNIQUE INDEX "employee_branch_assignments_employeeId_branchId_validFrom_key" ON "employee_branch_assignments"("employeeId", "branchId", "validFrom");

-- CreateIndex
CREATE UNIQUE INDEX "branches_odooBranchId_key" ON "branches"("odooBranchId");

-- AddForeignKey
ALTER TABLE "employee_branch_assignments" ADD CONSTRAINT "employee_branch_assignments_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "employee_branch_assignments" ADD CONSTRAINT "employee_branch_assignments_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

